# Generated by Django 5.1.6 on 2025-05-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_articles_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={},
        ),
        migrations.RemoveField(
            model_name='articles',
            name='announcement',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='text',
        ),
        migrations.AddField(
            model_name='articles',
            name='anons',
            field=models.CharField(default=1, max_length=300, verbose_name='Анонс'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articles',
            name='full_text',
            field=models.TextField(default=1, verbose_name='Текст статьи'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.DateField(verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
